### ISSUE TITLE
Cannot reach on Port 8443

### ISSUE THREAD

**Issue by chrauscher** [jbequinn/jsonsyncserver#68]
I have deployed the docker image on my portainer, but everdo says, that port 8443 (as mentioned in the compose file) is not reachable. Any clue?

**Comment by jbequinn** [comment]
Wow. I totally missed this one. I'm sorry. I think there's a mistake in the README. The Docker internal port is not 443, but 8443. The docker compose file should look like this:
```
ports:
  - target: 8443
    published: 8443
```
This works for me. You can verify if the service is reachable f.e. by trying to access the time endpoint:
```
$ curl -i -k https://localhost:8443/time

HTTP/1.1 401 Unauthorized
Content-Length: 0
```
Even if you don't supply username/password, you should still get a response from the service.

**Comment by jbequinn** [comment]
This issue was opened long ago and it may not be valid anymore, so I'll close it. Feel free to reopen it if still doesn't work for you.
